LOAD DATA
INFILE 'INPUT_FILE'
APPEND
INTO TABLE JOHN.TABLE2
FIELDS TERMINATED BY '	'
TRAILING NULLCOLS
(
CR_BUR_PTFLO_TYP_DESC char(255) NULLIF CR_BUR_PTFLO_TYP_DESC=BLANKS,
DW_PROD_SERV_FEE_PLN_RCD_ID,
DW_ULT_PROD_SERV_ID,
ACCT_NBR,
ACCT_GRP_NBR,
APPL_CDE,
PRCS_GRP_NBR,
FEE_CAT_CDE,
FEE_PLN_NBR,
FEE_DESC,
FEE_TYP_CDE,
FEE_EARN_CDE,
CMPT_1_NXT_ASSMT_DTE     DATE "YYYY-MM-DD",
CMPT_2_NXT_ASSMT_DTE     DATE "YYYY-MM-DD",
CMPT_3_NXT_ASSMT_DTE     DATE "YYYY-MM-DD",
CUR_PMT_DUE_DTE          DATE "YYYY-MM-DD",
EARN_GOOD_THRU_1_DTE     DATE "YYYY-MM-DD",
EARN_GOOD_THRU_2_DTE     DATE "YYYY-MM-DD",
PR_PMT_DUE_DTE           DATE "YYYY-MM-DD",
NXT_PMT_DUE_DTE          DATE "YYYY-MM-DD",
DW_ASP_ID,
CLNT_ID,
CUR_REC_IND,
SOR_EXP_DTE             "NVL(:SOR_EXP_DTE,'4444-12-31')",
EFF_DTE                 DATE "YYYY-MM-DD"
)

