//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:57:01 PM EDT 
//


package com.manh.inegration.iom.calendar;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CALENDAR_NAME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CALENDAR_DESCRIPTION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CARRIER_CODE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EFFECTIVE_DTTM" type="{}StringDate"/>
 *         &lt;element name="EXPIRATION_DTTM" type="{}StringDate"/>
 *         &lt;element name="SHIFT_LENGTH">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="13"/>
 *               &lt;fractionDigits value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NO_CONS_DAYS_ALLOWED_PW">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MARK_FOR_DELETION">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CALENDAR_DTL" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="WEEK_SEQ">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;totalDigits value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="START_DAYOFWEEK">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Sunday"/>
 *                         &lt;enumeration value="Monday"/>
 *                         &lt;enumeration value="Tuesday"/>
 *                         &lt;enumeration value="Wednesday"/>
 *                         &lt;enumeration value="Thursday"/>
 *                         &lt;enumeration value="Friday"/>
 *                         &lt;enumeration value="Saturday"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="START_DTTM" type="{}StringTime"/>
 *                   &lt;element name="END_DAYOFWEEK">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Sunday"/>
 *                         &lt;enumeration value="Monday"/>
 *                         &lt;enumeration value="Tuesday"/>
 *                         &lt;enumeration value="Wednesday"/>
 *                         &lt;enumeration value="Thursday"/>
 *                         &lt;enumeration value="Friday"/>
 *                         &lt;enumeration value="Saturday"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="END_DTTM" type="{}StringTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "calendarname",
    "calendardescription",
    "carriercode",
    "effectivedttm",
    "expirationdttm",
    "shiftlength",
    "noconsdaysallowedpw",
    "markfordeletion",
    "calendardtl"
})
public class Calendar {

    @XmlElement(name = "CALENDAR_NAME", required = true)
    protected String calendarname;
    @XmlElementRef(name = "CALENDAR_DESCRIPTION", type = JAXBElement.class, required = false)
    protected JAXBElement<String> calendardescription;
    @XmlElementRef(name = "CARRIER_CODE", type = JAXBElement.class, required = false)
    protected JAXBElement<String> carriercode;
    @XmlElement(name = "EFFECTIVE_DTTM", required = true)
    protected String effectivedttm;
    @XmlElement(name = "EXPIRATION_DTTM", required = true)
    protected String expirationdttm;
    @XmlElement(name = "SHIFT_LENGTH", required = true)
    protected BigDecimal shiftlength;
    @XmlElement(name = "NO_CONS_DAYS_ALLOWED_PW", required = true)
    protected BigInteger noconsdaysallowedpw;
    @XmlElement(name = "MARK_FOR_DELETION", required = true)
    protected String markfordeletion;
    @XmlElement(name = "CALENDAR_DTL", required = true)
    protected List<CALENDARDTL> calendardtl;

    /**
     * Gets the value of the calendarname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCALENDARNAME() {
        return calendarname;
    }

    /**
     * Sets the value of the calendarname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCALENDARNAME(String value) {
        this.calendarname = value;
    }

    /**
     * Gets the value of the calendardescription property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCALENDARDESCRIPTION() {
        return calendardescription;
    }

    /**
     * Sets the value of the calendardescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCALENDARDESCRIPTION(JAXBElement<String> value) {
        this.calendardescription = value;
    }

    /**
     * Gets the value of the carriercode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCARRIERCODE() {
        return carriercode;
    }

    /**
     * Sets the value of the carriercode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCARRIERCODE(JAXBElement<String> value) {
        this.carriercode = value;
    }

    /**
     * Gets the value of the effectivedttm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEFFECTIVEDTTM() {
        return effectivedttm;
    }

    /**
     * Sets the value of the effectivedttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEFFECTIVEDTTM(String value) {
        this.effectivedttm = value;
    }

    /**
     * Gets the value of the expirationdttm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPIRATIONDTTM() {
        return expirationdttm;
    }

    /**
     * Sets the value of the expirationdttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPIRATIONDTTM(String value) {
        this.expirationdttm = value;
    }

    /**
     * Gets the value of the shiftlength property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSHIFTLENGTH() {
        return shiftlength;
    }

    /**
     * Sets the value of the shiftlength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSHIFTLENGTH(BigDecimal value) {
        this.shiftlength = value;
    }

    /**
     * Gets the value of the noconsdaysallowedpw property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNOCONSDAYSALLOWEDPW() {
        return noconsdaysallowedpw;
    }

    /**
     * Sets the value of the noconsdaysallowedpw property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNOCONSDAYSALLOWEDPW(BigInteger value) {
        this.noconsdaysallowedpw = value;
    }

    /**
     * Gets the value of the markfordeletion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMARKFORDELETION() {
        return markfordeletion;
    }

    /**
     * Sets the value of the markfordeletion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMARKFORDELETION(String value) {
        this.markfordeletion = value;
    }

    /**
     * Gets the value of the calendardtl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the calendardtl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCALENDARDTL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CALENDARDTL }
     * 
     * 
     */
    public List<CALENDARDTL> getCALENDARDTL() {
        if (calendardtl == null) {
            calendardtl = new ArrayList<CALENDARDTL>();
        }
        return this.calendardtl;
    }

}
