//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:57:01 PM EDT 
//


package com.manh.inegration.iom.calendar;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WEEK_SEQ">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;totalDigits value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="START_DAYOFWEEK">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Sunday"/>
 *               &lt;enumeration value="Monday"/>
 *               &lt;enumeration value="Tuesday"/>
 *               &lt;enumeration value="Wednesday"/>
 *               &lt;enumeration value="Thursday"/>
 *               &lt;enumeration value="Friday"/>
 *               &lt;enumeration value="Saturday"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="START_DTTM" type="{}StringTime"/>
 *         &lt;element name="END_DAYOFWEEK">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Sunday"/>
 *               &lt;enumeration value="Monday"/>
 *               &lt;enumeration value="Tuesday"/>
 *               &lt;enumeration value="Wednesday"/>
 *               &lt;enumeration value="Thursday"/>
 *               &lt;enumeration value="Friday"/>
 *               &lt;enumeration value="Saturday"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="END_DTTM" type="{}StringTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "weekseq",
    "startdayofweek",
    "startdttm",
    "enddayofweek",
    "enddttm"
})
public class CALENDARDTL {

    @XmlElement(name = "WEEK_SEQ", required = true)
    protected BigInteger weekseq;
    @XmlElement(name = "START_DAYOFWEEK", required = true)
    protected String startdayofweek;
    @XmlElement(name = "START_DTTM", required = true)
    protected String startdttm;
    @XmlElement(name = "END_DAYOFWEEK", required = true)
    protected String enddayofweek;
    @XmlElement(name = "END_DTTM", required = true)
    protected String enddttm;

    /**
     * Gets the value of the weekseq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWEEKSEQ() {
        return weekseq;
    }

    /**
     * Sets the value of the weekseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWEEKSEQ(BigInteger value) {
        this.weekseq = value;
    }

    /**
     * Gets the value of the startdayofweek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTARTDAYOFWEEK() {
        return startdayofweek;
    }

    /**
     * Sets the value of the startdayofweek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTARTDAYOFWEEK(String value) {
        this.startdayofweek = value;
    }

    /**
     * Gets the value of the startdttm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTARTDTTM() {
        return startdttm;
    }

    /**
     * Sets the value of the startdttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTARTDTTM(String value) {
        this.startdttm = value;
    }

    /**
     * Gets the value of the enddayofweek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENDDAYOFWEEK() {
        return enddayofweek;
    }

    /**
     * Sets the value of the enddayofweek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENDDAYOFWEEK(String value) {
        this.enddayofweek = value;
    }

    /**
     * Gets the value of the enddttm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENDDTTM() {
        return enddttm;
    }

    /**
     * Sets the value of the enddttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENDDTTM(String value) {
        this.enddttm = value;
    }

}
