//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 04:57:01 PM EDT 
//


package com.manh.inegration.iom.calendar;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.manh.inegration.iom.calendar package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HeaderUserID_QNAME = new QName("", "User_ID");
    private final static QName _HeaderExternalDateTimeStamp_QNAME = new QName("", "External_Date_Time_Stamp");
    private final static QName _HeaderMsgLocale_QNAME = new QName("", "Msg_Locale");
    private final static QName _HeaderReferenceID_QNAME = new QName("", "Reference_ID");
    private final static QName _HeaderInternalDateTimeStamp_QNAME = new QName("", "Internal_Date_Time_Stamp");
    private final static QName _HeaderPassword_QNAME = new QName("", "Password");
    private final static QName _HeaderInternalReferenceID_QNAME = new QName("", "Internal_Reference_ID");
    private final static QName _HeaderExternalReferenceID_QNAME = new QName("", "External_Reference_ID");
    private final static QName _HeaderBatchID_QNAME = new QName("", "Batch_ID");
    private final static QName _HeaderMsgTimeZone_QNAME = new QName("", "Msg_Time_Zone");
    private final static QName _HeaderSequenceNumber_QNAME = new QName("", "Sequence_Number");
    private final static QName _HeaderBatchSize_QNAME = new QName("", "Batch_Size");
    private final static QName _HeaderVersion_QNAME = new QName("", "Version");
    private final static QName _HeaderDestination_QNAME = new QName("", "Destination");
    private final static QName _CalendarCALENDARDESCRIPTION_QNAME = new QName("", "CALENDAR_DESCRIPTION");
    private final static QName _CalendarCARRIERCODE_QNAME = new QName("", "CARRIER_CODE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.manh.inegration.iom.calendar
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TXML }
     * 
     */
    public TXML createTXML() {
        return new TXML();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link Calendar }
     * 
     */
    public Calendar createCalendar() {
        return new Calendar();
    }

    /**
     * Create an instance of {@link CALENDARDTL }
     * 
     */
    public CALENDARDTL createCALENDARDTL() {
        return new CALENDARDTL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "User_ID", scope = Header.class)
    public JAXBElement<String> createHeaderUserID(String value) {
        return new JAXBElement<String>(_HeaderUserID_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "External_Date_Time_Stamp", scope = Header.class)
    public JAXBElement<String> createHeaderExternalDateTimeStamp(String value) {
        return new JAXBElement<String>(_HeaderExternalDateTimeStamp_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Msg_Locale", scope = Header.class)
    public JAXBElement<String> createHeaderMsgLocale(String value) {
        return new JAXBElement<String>(_HeaderMsgLocale_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Reference_ID", scope = Header.class)
    public JAXBElement<String> createHeaderReferenceID(String value) {
        return new JAXBElement<String>(_HeaderReferenceID_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Internal_Date_Time_Stamp", scope = Header.class)
    public JAXBElement<String> createHeaderInternalDateTimeStamp(String value) {
        return new JAXBElement<String>(_HeaderInternalDateTimeStamp_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Password", scope = Header.class)
    public JAXBElement<String> createHeaderPassword(String value) {
        return new JAXBElement<String>(_HeaderPassword_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Internal_Reference_ID", scope = Header.class)
    public JAXBElement<String> createHeaderInternalReferenceID(String value) {
        return new JAXBElement<String>(_HeaderInternalReferenceID_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "External_Reference_ID", scope = Header.class)
    public JAXBElement<String> createHeaderExternalReferenceID(String value) {
        return new JAXBElement<String>(_HeaderExternalReferenceID_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Batch_ID", scope = Header.class)
    public JAXBElement<String> createHeaderBatchID(String value) {
        return new JAXBElement<String>(_HeaderBatchID_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Msg_Time_Zone", scope = Header.class)
    public JAXBElement<String> createHeaderMsgTimeZone(String value) {
        return new JAXBElement<String>(_HeaderMsgTimeZone_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sequence_Number", scope = Header.class)
    public JAXBElement<String> createHeaderSequenceNumber(String value) {
        return new JAXBElement<String>(_HeaderSequenceNumber_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Batch_Size", scope = Header.class)
    public JAXBElement<String> createHeaderBatchSize(String value) {
        return new JAXBElement<String>(_HeaderBatchSize_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version", scope = Header.class)
    public JAXBElement<String> createHeaderVersion(String value) {
        return new JAXBElement<String>(_HeaderVersion_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Destination", scope = Header.class)
    public JAXBElement<String> createHeaderDestination(String value) {
        return new JAXBElement<String>(_HeaderDestination_QNAME, String.class, Header.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CALENDAR_DESCRIPTION", scope = Calendar.class)
    public JAXBElement<String> createCalendarCALENDARDESCRIPTION(String value) {
        return new JAXBElement<String>(_CalendarCALENDARDESCRIPTION_QNAME, String.class, Calendar.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CARRIER_CODE", scope = Calendar.class)
    public JAXBElement<String> createCalendarCARRIERCODE(String value) {
        return new JAXBElement<String>(_CalendarCARRIERCODE_QNAME, String.class, Calendar.class, value);
    }

}
