
package com.example.services.helloworld;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI IBM 2.0_03-06/12/2007 07:44 PM(Raja)-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "HelloWorldSEI", targetNamespace = "http://www.example.com/services/HelloWorld")
public interface HelloWorldSEI {


    /**
     * 
     * @param message
     */
    @WebMethod(action = "hello")
    @RequestWrapper(localName = "hello", targetNamespace = "http://www.example.com/schemas/HelloWorld", className = "com.example.schemas.helloworld.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://www.example.com/schemas/HelloWorld", className = "com.example.schemas.helloworld.HelloResponse")
    public void hello(
        @WebParam(name = "message", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<String> message);

}
