
package com.example.services.banking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI IBM 2.0_03-06/12/2007 07:44 PM(Raja)-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BankingSEI", targetNamespace = "http://www.example.com/services/Banking")
public interface BankingSEI {


    /**
     * 
     * @param initialBalance
     * @param owner
     * @return
     *     returns long
     */
    @WebMethod(action = "createAccount")
    @WebResult(name = "accountNumber", targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://www.example.com/schemas/Banking", className = "com.example.schemas.banking.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://www.example.com/schemas/Banking", className = "com.example.schemas.banking.CreateAccountResponse")
    public long createAccount(
        @WebParam(name = "owner", targetNamespace = "")
        String owner,
        @WebParam(name = "initialBalance", targetNamespace = "")
        double initialBalance);

    /**
     * 
     * @param accountNumber
     * @param amount
     * @throws InsufficientFunds
     */
    @WebMethod(action = "withdraw")
    @RequestWrapper(localName = "withdraw", targetNamespace = "http://www.example.com/schemas/Banking", className = "com.example.schemas.banking.Withdraw")
    @ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://www.example.com/schemas/Banking", className = "com.example.schemas.banking.WithdrawResponse")
    public void withdraw(
        @WebParam(name = "accountNumber", targetNamespace = "")
        long accountNumber,
        @WebParam(name = "amount", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<Double> amount)
        throws InsufficientFunds
    ;

    /**
     * 
     * @param owner
     * @param accountNumber
     * @param balance
     */
    @WebMethod(action = "getAccountInfo")
    @RequestWrapper(localName = "getAccountInfo", targetNamespace = "http://www.example.com/schemas/Banking", className = "com.example.schemas.banking.GetAccountInfo")
    @ResponseWrapper(localName = "getAccountInfoResponse", targetNamespace = "http://www.example.com/schemas/Banking", className = "com.example.schemas.banking.GetAccountInfoResponse")
    public void getAccountInfo(
        @WebParam(name = "accountNumber", targetNamespace = "")
        long accountNumber,
        @WebParam(name = "balance", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Double> balance,
        @WebParam(name = "owner", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> owner);

}
