
package com.example.services.helloworld;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI IBM 2.0_03-06/12/2007 07:44 PM(Raja)-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "HelloService", targetNamespace = "http://www.example.com/services/HelloWorld", wsdlLocation = "WEB-INF/wsdl/hello.wsdl")
public class HelloService
    extends Service
{

    private final static URL HELLOSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/WEB-INF/wsdl/hello.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        HELLOSERVICE_WSDL_LOCATION = url;
    }

    public HelloService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloService() {
        super(HELLOSERVICE_WSDL_LOCATION, new QName("http://www.example.com/services/HelloWorld", "HelloService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldSEI
     */
    @WebEndpoint(name = "HelloPort")
    public HelloWorldSEI getHelloPort() {
        return (HelloWorldSEI)super.getPort(new QName("http://www.example.com/services/HelloWorld", "HelloPort"), HelloWorldSEI.class);
    }

}
