package mr.shravan.examples.drools
 
import mr.shravan.examples.domain.Bank;
import mr.shravan.examples.domain.Customer;
import mr.shravan.examples.domain.Account;


rule "Rule-1"
    when
        m: Bank()
        c: Customer()
        a: Account()
        eval(m.addCustomer(c,a))
        //eval(m.retTrue())
        
    then
        
        System.out.println("Migraiton rule test complete " );
        
end


rule "Bank Active Rule"
    when
        m : Bank( status == Bank.INACTIVE, message : message )
    then
        
        System.out.println( "Before: "+ message );
        
	    modify (m) {
	     setMessage("Set account as active"),
	     setStatus(Bank.ACTIVE) 
	    };
end



rule "Bank Active Status"
    when
        m : Bank( status == Bank.ACTIVE, message : message )
    then
        System.out.println( "After: "+message );
end
