package emp;


/**
* emp/_ManagerStub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from emp.idl
* Sunday, June 16, 2002 6:43:16 PM IST
*/

public class _ManagerStub extends org.omg.CORBA.portable.ObjectImpl implements emp.Manager
{
  // Constructors
  // NOTE:  If the default constructor is used, the
  //        object is useless until _set_delegate (...)
  //        is called.
  public _ManagerStub ()
  {
    super ();
  }

  public _ManagerStub (org.omg.CORBA.portable.Delegate delegate)
  {
    super ();
    _set_delegate (delegate);
  }

  public emp.Employee getEmployee (int empid) throws emp.EmployeeNotFound
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("getEmployee", true);
       _out.write_long (empid);
       _in = _invoke (_out);
       emp.Employee __result = emp.EmployeeHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       if (_id.equals ("IDL:emp/EmployeeNotFound:1.0"))
          throw emp.EmployeeNotFoundHelper.read (_in);
       else
            throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return getEmployee (empid);
    } finally {
        _releaseReply (_in);
    }
  } // getEmployee

  public emp.Employee[] getAll ()
  {
    org.omg.CORBA.portable.InputStream _in = null;
    try {
       org.omg.CORBA.portable.OutputStream _out = _request ("getAll", true);
       _in = _invoke (_out);
       emp.Employee __result[] = emp.EmployeeSeqHelper.read (_in);
       return __result;
    } catch (org.omg.CORBA.portable.ApplicationException _ex) {
       _in = _ex.getInputStream ();
       String _id = _ex.getId ();
       throw new org.omg.CORBA.MARSHAL (_id);
    } catch (org.omg.CORBA.portable.RemarshalException _rm) {
       return getAll ();
    } finally {
        _releaseReply (_in);
    }
  } // getAll

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:emp/Manager:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s)
  {
     try 
     {
       String str = s.readUTF ();
       org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init ().string_to_object (str);
       org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
       _set_delegate (delegate);
     } catch (java.io.IOException e) {}
  }

  private void writeObject (java.io.ObjectOutputStream s)
  {
     try 
     {
       String str = org.omg.CORBA.ORB.init ().object_to_string (this);
       s.writeUTF (str);
     } catch (java.io.IOException e) {}
  }
} // class _ManagerStub
