package emp;


/**
* emp/EmployeeNotFound.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from emp.idl
* Sunday, June 16, 2002 6:43:16 PM IST
*/

public final class EmployeeNotFound extends org.omg.CORBA.UserException implements org.omg.CORBA.portable.IDLEntity
{
  public String message = null;

  public EmployeeNotFound ()
  {
  } // ctor

  public EmployeeNotFound (String _message)
  {
    message = _message;
  } // ctor

} // class EmployeeNotFound
