package emp;

/**
* emp/EmployeeHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from emp.idl
* Sunday, June 16, 2002 6:43:16 PM IST
*/

public final class EmployeeHolder implements org.omg.CORBA.portable.Streamable
{
  public emp.Employee value = null;

  public EmployeeHolder ()
  {
  }

  public EmployeeHolder (emp.Employee initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = emp.EmployeeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    emp.EmployeeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return emp.EmployeeHelper.type ();
  }

}
