package emp;


/**
* emp/Employee.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from emp.idl
* Sunday, June 16, 2002 6:43:16 PM IST
*/

public final class Employee implements org.omg.CORBA.portable.IDLEntity
{
  public int empno = (int)0;
  public String ename = null;
  public float sal = (float)0;

  public Employee ()
  {
  } // ctor

  public Employee (int _empno, String _ename, float _sal)
  {
    empno = _empno;
    ename = _ename;
    sal = _sal;
  } // ctor

} // class Employee
