package emp;


/**
* emp/ManagerOperations.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from emp.idl
* Sunday, June 16, 2002 6:43:16 PM IST
*/

public interface ManagerOperations 
{
  emp.Employee getEmployee (int empid) throws emp.EmployeeNotFound;
  emp.Employee[] getAll ();
} // interface ManagerOperations
