package mr.shravan.examples.drools
 
import mr.shravan.examples.drools.DroolsExample.Message;

global java.util.List list
 
rule "Hello World"
    dialect "mvel"
    when
        m : Message( status == Message.HELLO, message : message )
    then
        System.out.println( "Before: "+message );
//        modify ( m ) { setMessage( "Goodbyte cruel world" ),
//                       setStatus( Message.GOODBYE ) };
    modify ( m ) { message = "Goodbye cruel world",
                   status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
        Message( status == Message.GOODBYE, $message : message )
    then
        System.out.println( $message );
end
