package emp;


/**
* emp/EmployeeNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from emp.idl
* Wednesday, October 17, 2012 5:46:25 PM EDT
*/

public final class EmployeeNotFound extends org.omg.CORBA.UserException
{
  public String message = null;

  public EmployeeNotFound ()
  {
    super(EmployeeNotFoundHelper.id());
  } // ctor

  public EmployeeNotFound (String _message)
  {
    super(EmployeeNotFoundHelper.id());
    message = _message;
  } // ctor


  public EmployeeNotFound (String $reason, String _message)
  {
    super(EmployeeNotFoundHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class EmployeeNotFound
