package emp;


/**
* emp/ManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from emp.idl
* Wednesday, October 17, 2012 5:46:25 PM EDT
*/

public abstract class ManagerPOA extends org.omg.PortableServer.Servant
 implements emp.ManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getEmployee", new java.lang.Integer (0));
    _methods.put ("getAll", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // emp/Manager/getEmployee
       {
         try {
           int empid = in.read_long ();
           emp.Employee $result = null;
           $result = this.getEmployee (empid);
           out = $rh.createReply();
           emp.EmployeeHelper.write (out, $result);
         } catch (emp.EmployeeNotFound $ex) {
           out = $rh.createExceptionReply ();
           emp.EmployeeNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // emp/Manager/getAll
       {
         emp.Employee $result[] = null;
         $result = this.getAll ();
         out = $rh.createReply();
         emp.EmployeeSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:emp/Manager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Manager _this() 
  {
    return ManagerHelper.narrow(
    super._this_object());
  }

  public Manager _this(org.omg.CORBA.ORB orb) 
  {
    return ManagerHelper.narrow(
    super._this_object(orb));
  }


} // class ManagerPOA
