package emp;


/**
* emp/ManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from emp.idl
* Wednesday, October 17, 2012 5:46:25 PM EDT
*/

public interface ManagerOperations 
{
  emp.Employee getEmployee (int empid) throws emp.EmployeeNotFound;
  emp.Employee[] getAll ();
} // interface ManagerOperations
