package emp;

/**
* emp/ManagerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from emp.idl
* Wednesday, October 17, 2012 5:46:25 PM EDT
*/

public final class ManagerHolder implements org.omg.CORBA.portable.Streamable
{
  public emp.Manager value = null;

  public ManagerHolder ()
  {
  }

  public ManagerHolder (emp.Manager initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = emp.ManagerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    emp.ManagerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return emp.ManagerHelper.type ();
  }

}
