//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 05:49:19 PM EDT 
//


package mr.shravan.examples.translators.iom.dord;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccessorialOptionGroup" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AccessorialGroupCode" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="DVL"/>
 *                         &lt;enumeration value="AH"/>
 *                         &lt;enumeration value="AH2"/>
 *                         &lt;enumeration value="LPS"/>
 *                         &lt;enumeration value="ELG"/>
 *                         &lt;enumeration value="ELL"/>
 *                         &lt;enumeration value="ELW"/>
 *                         &lt;enumeration value="EPL"/>
 *                         &lt;enumeration value="ESL"/>
 *                         &lt;enumeration value="NON"/>
 *                         &lt;enumeration value="FUE"/>
 *                         &lt;enumeration value="RES"/>
 *                         &lt;enumeration value="HRS"/>
 *                         &lt;enumeration value="HLD"/>
 *                         &lt;enumeration value="SAP"/>
 *                         &lt;enumeration value="SAT"/>
 *                         &lt;enumeration value="BDT"/>
 *                         &lt;enumeration value="DDP"/>
 *                         &lt;enumeration value="DPU"/>
 *                         &lt;enumeration value="ECL"/>
 *                         &lt;enumeration value="NDS"/>
 *                         &lt;enumeration value="COA"/>
 *                         &lt;enumeration value="CON"/>
 *                         &lt;enumeration value="COS"/>
 *                         &lt;enumeration value="VCD"/>
 *                         &lt;enumeration value="CODA"/>
 *                         &lt;enumeration value="COD"/>
 *                         &lt;enumeration value="ECDA"/>
 *                         &lt;enumeration value="ECD"/>
 *                         &lt;enumeration value="RT1"/>
 *                         &lt;enumeration value="RT3"/>
 *                         &lt;enumeration value="IND"/>
 *                         &lt;enumeration value="INP"/>
 *                         &lt;enumeration value="AKM"/>
 *                         &lt;enumeration value="HIM"/>
 *                         &lt;enumeration value="LAM"/>
 *                         &lt;enumeration value="EML"/>
 *                         &lt;enumeration value="QVE"/>
 *                         &lt;enumeration value="QVF"/>
 *                         &lt;enumeration value="QVX"/>
 *                         &lt;enumeration value="QVD"/>
 *                         &lt;enumeration value="PA"/>
 *                         &lt;enumeration value="SA"/>
 *                         &lt;enumeration value="DCN"/>
 *                         &lt;enumeration value="EVE"/>
 *                         &lt;enumeration value="APP"/>
 *                         &lt;enumeration value="DS1"/>
 *                         &lt;enumeration value="DS2"/>
 *                         &lt;enumeration value="EAS"/>
 *                         &lt;enumeration value="ONF"/>
 *                         &lt;enumeration value="IAS"/>
 *                         &lt;enumeration value="RTP"/>
 *                         &lt;enumeration value="LVE"/>
 *                         &lt;enumeration value="RSR"/>
 *                         &lt;enumeration value="SED"/>
 *                         &lt;enumeration value="CO"/>
 *                         &lt;enumeration value="CI"/>
 *                         &lt;enumeration value="MIT"/>
 *                         &lt;enumeration value="TEN"/>
 *                         &lt;enumeration value=""/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accessorialOptionGroup"
})
public class AccessorialOptionGroupList {

    @XmlElement(name = "AccessorialOptionGroup")
    protected List<AccessorialOptionGroup> accessorialOptionGroup;

    /**
     * Gets the value of the accessorialOptionGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessorialOptionGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessorialOptionGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessorialOptionGroup }
     * 
     * 
     */
    public List<AccessorialOptionGroup> getAccessorialOptionGroup() {
        if (accessorialOptionGroup == null) {
            accessorialOptionGroup = new ArrayList<AccessorialOptionGroup>();
        }
        return this.accessorialOptionGroup;
    }

}
