//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 05:49:19 PM EDT 
//


package mr.shravan.examples.translators.iom.dord;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CommodityClassCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="FAK"/>
 *               &lt;enumeration value="50"/>
 *               &lt;enumeration value="55"/>
 *               &lt;enumeration value="60"/>
 *               &lt;enumeration value="65"/>
 *               &lt;enumeration value="70"/>
 *               &lt;enumeration value="77.5"/>
 *               &lt;enumeration value="85"/>
 *               &lt;enumeration value="92.5"/>
 *               &lt;enumeration value="100"/>
 *               &lt;enumeration value="110"/>
 *               &lt;enumeration value="125"/>
 *               &lt;enumeration value="150"/>
 *               &lt;enumeration value="175"/>
 *               &lt;enumeration value="200"/>
 *               &lt;enumeration value="250"/>
 *               &lt;enumeration value="300"/>
 *               &lt;enumeration value="400"/>
 *               &lt;enumeration value="500"/>
 *               &lt;enumeration value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Size" type="{}SizeForCommodity" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "commodityClassCode",
    "size"
})
public class CommoditySize {

    @XmlElementRef(name = "CommodityClassCode", type = JAXBElement.class, required = false)
    protected JAXBElement<String> commodityClassCode;
    @XmlElement(name = "Size", required = true)
    protected List<SizeForCommodity> size;

    /**
     * Gets the value of the commodityClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getCommodityClassCode() {
        return commodityClassCode;
    }

    /**
     * Sets the value of the commodityClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setCommodityClassCode(JAXBElement<String> value) {
        this.commodityClassCode = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the size property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SizeForCommodity }
     * 
     * 
     */
    public List<SizeForCommodity> getSize() {
        if (size == null) {
            size = new ArrayList<SizeForCommodity>();
        }
        return this.size;
    }

}
