//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 05:49:19 PM EDT 
//


package mr.shravan.examples.translators.iom.dord;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineItemType1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LineItemType1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DoLineNbr">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Quantity" type="{}Quantity"/>
 *         &lt;element name="Weight" type="{}Weight" minOccurs="0"/>
 *         &lt;element name="Volume" type="{}Volume" minOccurs="0"/>
 *         &lt;element name="Size1" type="{}Size1" minOccurs="0"/>
 *         &lt;element name="Size2" type="{}Size2" minOccurs="0"/>
 *         &lt;element name="Size" type="{}Size" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LineItemType1", propOrder = {
    "doLineNbr",
    "quantity",
    "weight",
    "volume",
    "size1",
    "size2",
    "size"
})
public class LineItemType1 {

    @XmlElement(name = "DoLineNbr", required = true)
    protected String doLineNbr;
    @XmlElement(name = "Quantity", required = true)
    protected Quantity quantity;
    @XmlElement(name = "Weight")
    protected Weight weight;
    @XmlElement(name = "Volume")
    protected Volume volume;
    @XmlElement(name = "Size1")
    protected Size1 size1;
    @XmlElement(name = "Size2")
    protected Size2 size2;
    @XmlElement(name = "Size")
    protected List<Size> size;

    /**
     * Gets the value of the doLineNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoLineNbr() {
        return doLineNbr;
    }

    /**
     * Sets the value of the doLineNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoLineNbr(String value) {
        this.doLineNbr = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link Quantity }
     *     
     */
    public Quantity getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantity }
     *     
     */
    public void setQuantity(Quantity value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link Weight }
     *     
     */
    public Weight getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weight }
     *     
     */
    public void setWeight(Weight value) {
        this.weight = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link Volume }
     *     
     */
    public Volume getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link Volume }
     *     
     */
    public void setVolume(Volume value) {
        this.volume = value;
    }

    /**
     * Gets the value of the size1 property.
     * 
     * @return
     *     possible object is
     *     {@link Size1 }
     *     
     */
    public Size1 getSize1() {
        return size1;
    }

    /**
     * Sets the value of the size1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Size1 }
     *     
     */
    public void setSize1(Size1 value) {
        this.size1 = value;
    }

    /**
     * Gets the value of the size2 property.
     * 
     * @return
     *     possible object is
     *     {@link Size2 }
     *     
     */
    public Size2 getSize2() {
        return size2;
    }

    /**
     * Sets the value of the size2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Size2 }
     *     
     */
    public void setSize2(Size2 value) {
        this.size2 = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the size property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Size }
     * 
     * 
     */
    public List<Size> getSize() {
        if (size == null) {
            size = new ArrayList<Size>();
        }
        return this.size;
    }

}
