//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 05:49:19 PM EDT 
//


package mr.shravan.examples.translators.iom.dord;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LineRefTextField1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField4" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField5" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField6" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField7" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField8" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField9" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefTextField10" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefNumberField1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefNumberField2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefNumberField3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefNumberField4" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LineRefNumberField5" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lineRefTextField1",
    "lineRefTextField2",
    "lineRefTextField3",
    "lineRefTextField4",
    "lineRefTextField5",
    "lineRefTextField6",
    "lineRefTextField7",
    "lineRefTextField8",
    "lineRefTextField9",
    "lineRefTextField10",
    "lineRefNumberField1",
    "lineRefNumberField2",
    "lineRefNumberField3",
    "lineRefNumberField4",
    "lineRefNumberField5"
})
public class LineProcessInfo {

    @XmlElementRef(name = "LineRefTextField1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField1;
    @XmlElementRef(name = "LineRefTextField2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField2;
    @XmlElementRef(name = "LineRefTextField3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField3;
    @XmlElementRef(name = "LineRefTextField4", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField4;
    @XmlElementRef(name = "LineRefTextField5", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField5;
    @XmlElementRef(name = "LineRefTextField6", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField6;
    @XmlElementRef(name = "LineRefTextField7", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField7;
    @XmlElementRef(name = "LineRefTextField8", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField8;
    @XmlElementRef(name = "LineRefTextField9", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField9;
    @XmlElementRef(name = "LineRefTextField10", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefTextField10;
    @XmlElementRef(name = "LineRefNumberField1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField1;
    @XmlElementRef(name = "LineRefNumberField2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField2;
    @XmlElementRef(name = "LineRefNumberField3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField3;
    @XmlElementRef(name = "LineRefNumberField4", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField4;
    @XmlElementRef(name = "LineRefNumberField5", type = JAXBElement.class, required = false)
    protected JAXBElement<String> lineRefNumberField5;

    /**
     * Gets the value of the lineRefTextField1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField1() {
        return lineRefTextField1;
    }

    /**
     * Sets the value of the lineRefTextField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField1(JAXBElement<String> value) {
        this.lineRefTextField1 = value;
    }

    /**
     * Gets the value of the lineRefTextField2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField2() {
        return lineRefTextField2;
    }

    /**
     * Sets the value of the lineRefTextField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField2(JAXBElement<String> value) {
        this.lineRefTextField2 = value;
    }

    /**
     * Gets the value of the lineRefTextField3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField3() {
        return lineRefTextField3;
    }

    /**
     * Sets the value of the lineRefTextField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField3(JAXBElement<String> value) {
        this.lineRefTextField3 = value;
    }

    /**
     * Gets the value of the lineRefTextField4 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField4() {
        return lineRefTextField4;
    }

    /**
     * Sets the value of the lineRefTextField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField4(JAXBElement<String> value) {
        this.lineRefTextField4 = value;
    }

    /**
     * Gets the value of the lineRefTextField5 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField5() {
        return lineRefTextField5;
    }

    /**
     * Sets the value of the lineRefTextField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField5(JAXBElement<String> value) {
        this.lineRefTextField5 = value;
    }

    /**
     * Gets the value of the lineRefTextField6 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField6() {
        return lineRefTextField6;
    }

    /**
     * Sets the value of the lineRefTextField6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField6(JAXBElement<String> value) {
        this.lineRefTextField6 = value;
    }

    /**
     * Gets the value of the lineRefTextField7 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField7() {
        return lineRefTextField7;
    }

    /**
     * Sets the value of the lineRefTextField7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField7(JAXBElement<String> value) {
        this.lineRefTextField7 = value;
    }

    /**
     * Gets the value of the lineRefTextField8 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField8() {
        return lineRefTextField8;
    }

    /**
     * Sets the value of the lineRefTextField8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField8(JAXBElement<String> value) {
        this.lineRefTextField8 = value;
    }

    /**
     * Gets the value of the lineRefTextField9 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField9() {
        return lineRefTextField9;
    }

    /**
     * Sets the value of the lineRefTextField9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField9(JAXBElement<String> value) {
        this.lineRefTextField9 = value;
    }

    /**
     * Gets the value of the lineRefTextField10 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefTextField10() {
        return lineRefTextField10;
    }

    /**
     * Sets the value of the lineRefTextField10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefTextField10(JAXBElement<String> value) {
        this.lineRefTextField10 = value;
    }

    /**
     * Gets the value of the lineRefNumberField1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField1() {
        return lineRefNumberField1;
    }

    /**
     * Sets the value of the lineRefNumberField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField1(JAXBElement<String> value) {
        this.lineRefNumberField1 = value;
    }

    /**
     * Gets the value of the lineRefNumberField2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField2() {
        return lineRefNumberField2;
    }

    /**
     * Sets the value of the lineRefNumberField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField2(JAXBElement<String> value) {
        this.lineRefNumberField2 = value;
    }

    /**
     * Gets the value of the lineRefNumberField3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField3() {
        return lineRefNumberField3;
    }

    /**
     * Sets the value of the lineRefNumberField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField3(JAXBElement<String> value) {
        this.lineRefNumberField3 = value;
    }

    /**
     * Gets the value of the lineRefNumberField4 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField4() {
        return lineRefNumberField4;
    }

    /**
     * Sets the value of the lineRefNumberField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField4(JAXBElement<String> value) {
        this.lineRefNumberField4 = value;
    }

    /**
     * Gets the value of the lineRefNumberField5 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getLineRefNumberField5() {
        return lineRefNumberField5;
    }

    /**
     * Sets the value of the lineRefNumberField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setLineRefNumberField5(JAXBElement<String> value) {
        this.lineRefNumberField5 = value;
    }

}
