//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.28 at 05:49:19 PM EDT 
//


package mr.shravan.examples.translators.iom.dord;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RefTextField1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField4" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField5" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField6" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField7" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField8" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField9" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefTextField10" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefNumberField1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefNumberField2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefNumberField3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefNumberField4" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RefNumberField5" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;union>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                   &lt;totalDigits value="13"/>
 *                   &lt;fractionDigits value="5"/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *               &lt;simpleType>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                   &lt;enumeration value=""/>
 *                 &lt;/restriction>
 *               &lt;/simpleType>
 *             &lt;/union>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refTextField1",
    "refTextField2",
    "refTextField3",
    "refTextField4",
    "refTextField5",
    "refTextField6",
    "refTextField7",
    "refTextField8",
    "refTextField9",
    "refTextField10",
    "refNumberField1",
    "refNumberField2",
    "refNumberField3",
    "refNumberField4",
    "refNumberField5"
})
public class ProcessInfo {

    @XmlElementRef(name = "RefTextField1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField1;
    @XmlElementRef(name = "RefTextField2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField2;
    @XmlElementRef(name = "RefTextField3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField3;
    @XmlElementRef(name = "RefTextField4", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField4;
    @XmlElementRef(name = "RefTextField5", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField5;
    @XmlElementRef(name = "RefTextField6", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField6;
    @XmlElementRef(name = "RefTextField7", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField7;
    @XmlElementRef(name = "RefTextField8", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField8;
    @XmlElementRef(name = "RefTextField9", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField9;
    @XmlElementRef(name = "RefTextField10", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refTextField10;
    @XmlElementRef(name = "RefNumberField1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refNumberField1;
    @XmlElementRef(name = "RefNumberField2", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refNumberField2;
    @XmlElementRef(name = "RefNumberField3", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refNumberField3;
    @XmlElementRef(name = "RefNumberField4", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refNumberField4;
    @XmlElementRef(name = "RefNumberField5", type = JAXBElement.class, required = false)
    protected JAXBElement<String> refNumberField5;

    /**
     * Gets the value of the refTextField1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField1() {
        return refTextField1;
    }

    /**
     * Sets the value of the refTextField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField1(JAXBElement<String> value) {
        this.refTextField1 = value;
    }

    /**
     * Gets the value of the refTextField2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField2() {
        return refTextField2;
    }

    /**
     * Sets the value of the refTextField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField2(JAXBElement<String> value) {
        this.refTextField2 = value;
    }

    /**
     * Gets the value of the refTextField3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField3() {
        return refTextField3;
    }

    /**
     * Sets the value of the refTextField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField3(JAXBElement<String> value) {
        this.refTextField3 = value;
    }

    /**
     * Gets the value of the refTextField4 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField4() {
        return refTextField4;
    }

    /**
     * Sets the value of the refTextField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField4(JAXBElement<String> value) {
        this.refTextField4 = value;
    }

    /**
     * Gets the value of the refTextField5 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField5() {
        return refTextField5;
    }

    /**
     * Sets the value of the refTextField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField5(JAXBElement<String> value) {
        this.refTextField5 = value;
    }

    /**
     * Gets the value of the refTextField6 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField6() {
        return refTextField6;
    }

    /**
     * Sets the value of the refTextField6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField6(JAXBElement<String> value) {
        this.refTextField6 = value;
    }

    /**
     * Gets the value of the refTextField7 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField7() {
        return refTextField7;
    }

    /**
     * Sets the value of the refTextField7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField7(JAXBElement<String> value) {
        this.refTextField7 = value;
    }

    /**
     * Gets the value of the refTextField8 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField8() {
        return refTextField8;
    }

    /**
     * Sets the value of the refTextField8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField8(JAXBElement<String> value) {
        this.refTextField8 = value;
    }

    /**
     * Gets the value of the refTextField9 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField9() {
        return refTextField9;
    }

    /**
     * Sets the value of the refTextField9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField9(JAXBElement<String> value) {
        this.refTextField9 = value;
    }

    /**
     * Gets the value of the refTextField10 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefTextField10() {
        return refTextField10;
    }

    /**
     * Sets the value of the refTextField10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefTextField10(JAXBElement<String> value) {
        this.refTextField10 = value;
    }

    /**
     * Gets the value of the refNumberField1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefNumberField1() {
        return refNumberField1;
    }

    /**
     * Sets the value of the refNumberField1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefNumberField1(JAXBElement<String> value) {
        this.refNumberField1 = value;
    }

    /**
     * Gets the value of the refNumberField2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefNumberField2() {
        return refNumberField2;
    }

    /**
     * Sets the value of the refNumberField2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefNumberField2(JAXBElement<String> value) {
        this.refNumberField2 = value;
    }

    /**
     * Gets the value of the refNumberField3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefNumberField3() {
        return refNumberField3;
    }

    /**
     * Sets the value of the refNumberField3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefNumberField3(JAXBElement<String> value) {
        this.refNumberField3 = value;
    }

    /**
     * Gets the value of the refNumberField4 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefNumberField4() {
        return refNumberField4;
    }

    /**
     * Sets the value of the refNumberField4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefNumberField4(JAXBElement<String> value) {
        this.refNumberField4 = value;
    }

    /**
     * Gets the value of the refNumberField5 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getRefNumberField5() {
        return refNumberField5;
    }

    /**
     * Sets the value of the refNumberField5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRefNumberField5(JAXBElement<String> value) {
        this.refNumberField5 = value;
    }

}
