
package com.example.services.banking;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI IBM 2.0_03-06/12/2007 07:44 PM(Raja)-fcs
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "InsufficientFunds", targetNamespace = "http://www.example.com/schemas/Banking")
public class InsufficientFunds
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.example.schemas.banking.InsufficientFunds faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InsufficientFunds(String message, com.example.schemas.banking.InsufficientFunds faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public InsufficientFunds(String message, com.example.schemas.banking.InsufficientFunds faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.example.schemas.banking.InsufficientFunds
     */
    public com.example.schemas.banking.InsufficientFunds getFaultInfo() {
        return faultInfo;
    }

}
